# Generated by Django 4.2.1 on 2023-05-23 11:12

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('comment', models.TextField(max_length=500)),
                ('is_answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=25)),
                ('link', models.CharField(blank=True, default='#', max_length=150, null=True)),
                ('parent_id', models.IntegerField(default=0)),
                ('type', models.CharField(default='header', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RokhInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('email', models.EmailField(default='hanousa@gmail.com', max_length=254)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('image_url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('status', models.IntegerField(validators=[home.models.validate1or2])),
                ('image_url', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('link', models.TextField(default='#', null=True)),
                ('label', models.CharField(max_length=30)),
                ('image_url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=30)),
                ('ticket_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.contactus')),
            ],
        ),
    ]
